# Generated by Django 5.1.6 on 2025-02-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
