# Generated by Django 5.1.6 on 2025-03-12 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0002_submission_error_submission_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='input_format',
        ),
        migrations.RemoveField(
            model_name='question',
            name='output_format',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sample_input',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sample_output',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='codingapp.module'),
        ),
    ]
