# Generated by Django 5.1.6 on 2025-03-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0005_question_test_cases_alter_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_code',
            field=models.TextField(default=''),
        ),
    ]
