# Generated by Django 5.1.6 on 2025-03-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0006_submission_submitted_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='code',
        ),
    ]
